"""Frozen logical contract for the selected replaceable controller board."""

from __future__ import annotations

DEV_BOARD_MODEL = "ESP32-S3 SuperMini HW-747 V0.0.2 (ESP32-S3FH4R2)"
DEV_BOARD_HARDWARE_REVISION = "HW-747 V0.0.2"
ESP32_PART_NUMBER = "ESP32-S3FH4R2"
ESP32_IN_PACKAGE_FLASH_MB = 4
ESP32_IN_PACKAGE_PSRAM_MB = 2
ESP32_FLASH_INTERFACE = "Quad SPI"
ESP32_PSRAM_INTERFACE = "Quad SPI"
DEV_BOARD_PCB_LENGTH_MM_APPROX = 23.5
DEV_BOARD_WIDTH_MM_APPROX = 18.0
DEV_BOARD_LENGTH_WITH_USB_MM_APPROX = 25.0
DEV_BOARD_PIN_ROW_SPACING_MM_APPROX = 15.5
DEV_BOARD_ALONG_ROW_PIN_PITCH_MM = 2.54
DEV_BOARD_HEADER_ROWS = 2
DEV_BOARD_PINS_PER_HEADER_ROW = 9
DEV_BOARD_MALE_HEADERS_INSTALLED = True
DEV_BOARD_CARRIER_MOUNTING = "two 1x9 male headers into two 1x9 female carrier sockets"

LEFT_PINS_USB_UP = (
    "TX",
    "RX",
    "GPIO1",
    "GPIO2",
    "GPIO3",
    "GPIO4",
    "GPIO5",
    "GPIO6",
    "GPIO7",
)
RIGHT_PINS_USB_UP = (
    "5V",
    "GND",
    "3V3",
    "GPIO13",
    "GPIO12",
    "GPIO11",
    "GPIO10",
    "GPIO9",
    "GPIO8",
)

SENSOR_INPUT_GPIO = 4
START_STOP_BUTTON_GPIO = 5
READY_LED_GPIO = 8
REC_LED_GPIO = 9
EVENT_LED_GPIO = 10
PWR_LED_SOURCE = "3V3"

EXPOSED_STRAPPING_PINS = frozenset({3})
NATIVE_USB_GPIOS = frozenset({19, 20})
